language: java

jdk:
  - openjdk11

env:
  global:
    secure: "Z1mxq8+G1lXY/cUG8YAWjSkVOhxkMsrK6JVZG07OqRdhHuuMW2mh27x8yyalay/8/YUxBE9OWGFRtJs/BD6/zAk/xOSrn81RtTl8AM0+ybgfky/VaGLQbB2Yb3OP0YaU6V4HRSXoJcntEYCeu2LMnHGQuLgsDZCwdN+u9qJgfN2P/tnN1GLd5Xz77qHAjRIUMa1ehqzFVxs4GIhilMSVrwbLP+9ljiRlg/DBGaSsJFKa8XO82l2Fcslk9c0JL96YadrqcRhhp33xg3JR6ZyuSbk09ewIWU3Xccut0r+ZVaZDu5qwcEyW0Wofus3kqRCU1cnA/nYGDChuXoNTNhUCLQMIc6sko5GduMuTloGg2uhW2uikx0+5OS3nYiH/EPnklb8edfh7DJ+geS0Xm1Cd0WKoULRooSQKgEuxFRhNWb7EWK6Qg790iNtMb+/BFLY8kd0VixQMuRpDrbWkiJ+wH0zW9cyWQKPxhLAe60c3BxHjyQwwKsZCbVKsP2ZYbzfPmFiMMOjbUO3XYC0NDucsxJFKRENU3o6DJ8yf233DsNGxyU3udDjpq6ZZ4d5rpVTwURBhZu82Q5PpV63KZbrFZeUUNtTRJRfoaHEOzj0wA7VWvqma1Vi3XivzjR3nLgaMdXu0ifi1P08s27/MMejgZVrzV9VuRDwiAQdGwSTVFzY="
    secure: "lkyLHsvuIs5K0f8J58zQzW+6/OnpWMpj2zH3Uoc64kRv84cSiY2+l0YerbL44oIFYQXt9U0Tlr7DNH7ohMxD+Mma1RWuMzQ6KqmN0a37JShDJhVdOeboRNqEYUTpFkAztN8aFxFoKV5v/JTdFXTlMxjscJl/XSLdto8iW1/865A1vNaUUksDtKIUm3EMTkIb1TdikjJo0giXpg4t4tHLonB9DK+dZ0KDEPur0I/v3e/X0S0KBxsfu/4sE3708qPpu977HpZLwDlpsFZbSYxwbb2Vlpxca5xCxKv1rYc84HQC5TOp7dvL4StHjCJzo6fjl7Hw0OXosd3xo10SpHcIdirDKY7Np13ILNiGFzFg+tyCtNe5ujVIrT8aD1VQWctMsJsiETEbmslJ1ao4wqCVEBQdU0yqwGGC4RGVISWxK9PwgecPA5qMJ+elNzzlzx7kSZ8EAusUT1uHjaOns2UwSq5XwZBUxHmaS1j/sUhZ4Dya5Zte/c1jNmWbHIWUsqaj99hwmqT6m+PnkGbF7rx+JXrfpQnGBFFqPgqWbNp/qqm4QQ40aysrfd3jLCm85971JNYBUeMpZfUVpL2uab/aFyIImcte3FKjvV8U+Edyrg4u7T78Da5lwMfLB8phs+dQGhdAc/PBM8SmZgfoZFyYO/dJmmTJsM61Ef0VJnUCpV0="

install:
  mvn validate

script:
  mvn install pmd:pmd pmd:check

after_success:
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken="${PROJECT_TOKEN}" -DapiToken="${API_TOKEN}"

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_failure: change
    on_success: never
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always

sudo: false
